module.exports = {
  // Tutaj mówimy automatowi, skąd ma pobrać bazę (od Victora)
  based_on: {
    repo: "https://github.com/victorperin/ender_3_4.2.7_firmware",
    path: "/autogeneratedConfigs/auto_level/stable/latest", // ścieżka do wersji auto_level
    stable_branch: "main",
    nightly_branch: "main"
  },
  configuration: {
    enable: [
      ["GRID_MAX_POINTS_X", 7], // Zmiana siatki X na 7 punktów
      ["GRID_MAX_POINTS_Y", 7]  // Zmiana siatki Y na 7 punktów
    ]
  }
};
